Moved variable files to the user's homedir/.yombo. Moved install loction to /srv

diff --git a/ybo b/ybo
--- a/ybo
+++ b/ybo
@@ -2,79 +2,99 @@
 
 # a basic wrapper around the yombo.tac (yombo service).
 
-if [ "$EUID" -eq 0 ]; then
-    echo ""
-    echo "This should't be run by root. This should be run be a normal user."
-    echo ""
-    while true; do
-        read -p "Are you sure you want to do this? (y/n)" yn
-        case $yn in
-            [Yy]* ) break;;
-            [Nn]* ) exit;;
-            * ) echo "Please answer y (yes) or n (no).";;
-        esac
-    done
+if [ "$USER" = "root" ] && [ "$SUDO_USER" == "" ]; then
+  echo "This script cannot be run as root directly and must be run"
+  echo "as the user owning the Yombo gateway service."
+  echo ""
+  echo "Logout as root and then:"
+  echo "sudo ybo"
+  exit
 fi
 
-usage()
+if [ "$SUDO_USER" != "" ]; then
+  REALUSER=$SUDO_USER
+else
+  REALUSER=$USER
+fi
+SCRIPTPATH="$(dirname "$(readlink -f "$0")")"
+rc=$?
+if [[ $rc != 0 ]]; then
+ SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
+fi
+WORK_DIR="$HOME/.yombo"
+LOGCFGFILE=$WORK_DIR/log/config.log
+LOGFILE=$WORK_DIR/log/service.log
+
+function usage()
+{
+  printf "usage: ybo [options...]\\n"
+  printf "'ybo -help' to see all options\\n"
+  return 0
+}
+
+function help()
 {
 cat << EOF
-usage: ybo
+Manage and run the Yombo Gateway software
 
-Manages the Yombo gateway service or simply just starts it up
-in interactive mode.
+If no options are provided, starts the Yombo software in interactive mode.
 
-
-Get status and manage the Yombo Gateway software.
+ybo [-option(s)]
 
 OPTIONS:
-   -debug [items]      Turn on debug mode.
-   -disable
-       Disable Yombo service.
-   -enable
-       Enable Yombo service.
-   -h, -help           Show this message
-   -logfile FILE       Change log file location
-   -motd               Show MOTD / URL status
-   -profiler           Enable profiling to profile.out
-   -pid_path PATH      Set the pid path location
-   -pid_file FILE      Set the pid path filename
-   -start              Start Yombo service
-   -status             Show the status of the Yombo service
-   -stop               Stop Yombo service
-   -urls               Show URLs to access Yombo Gateway.
-   -working-dir DIR    Set data storage directory
-   -version            Show version
+  -debug [items]      Turn on debug mode.
+  -h, -help           Show this message
+  -logfile FILE       Change log file location
+  -motd               Show MOTD / URL status
+  -profiler           Enable profiling to profile.out
+  -pid_path PATH      Set the pid path location
+  -pid_file FILE      Set the pid path filename
+  -daemon              Start Yombo service (called by system to start the daemon)
+  -status             Show the status of the Yombo service
+  -urls               Show URLs to access Yombo Gateway.
+  -working-dir DIR    Set data storage directory
+  -version            Show version
 
-EXAMPLES:
+Examples:
   Debugging:
     Turn on debug with with optional selection of what items to debug. The
     items list can be * for all, or a comma separated list of items such as:
     --debug yombo.lib.*,yombo.modules.mymodule.*
 
+Additional Yombo Tools:
+  ybo-config - Configure Yombo Gateway service for '$REALUSER'
+
 EOF
 }
 
-TEMPSCRIPTPATH=$(readlink -f `which ybo`)
-rc=$?
-if [[ $rc != 0 ]]; then
- SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
-else
- SCRIPTPATH=$(dirname "$TEMPSCRIPTPATH")
-fi
-echo "results: $SCRIPTPATH"
-cd "$SCRIPTPATH"
+function show_status()
+{
+    if [ "$SHOW_STATUS" == "true" ]; then
+      if [ -e $PID_PATH/$PID_FILE ]; then
+        mypid=`cat $PID_PATH/$PID_FILE`
+        if kill -0 &>1 > /dev/null $mypid; then
+          echo "Yombo gateway appears to be running with pid: $mypid"
+          echo ""
+          $SCRIPTPATH/scripts/show_motd
+          exit 1
+        fi
+        echo "Yombo gateway is not running."
+      fi
+      exit 1
+    fi
+}
+
 
 #Base vars
 DAEMON=0
 DEBUG=false
 DEBUG_ITEMS=*
-LOGFILE=/var/log/yombo/yombo.log
 LOGENABLE=0
-PID_PATH=$HOME/.yombo/
+PID_PATH=$HOME/.yombo
 PID_FILE=yombo.pid
-TACFILE=yombo.tac
+TACFILE=$SCRIPTPATH/yombo.tac
 SHOW_STATUS=false
+TACFILE="$SCRIPTPATH/yombo.tac"
 
 ARGUMENTS=
 
@@ -85,6 +105,7 @@ while true; do
     -daemon)
       # Run as daemon (used by systemd)
       DAEMON=1
+      shift
       ;;
     -debug )
       ARGUMENTS="$ARGUMENTS -debug"
@@ -101,7 +122,7 @@ while true; do
       systemctl enable yombo
       exit 1
       shift ;;
-    -h | --help )
+    -h | --help | -? )
       usage
       exit 1
       ;;
@@ -138,7 +159,8 @@ while true; do
       exit 1
       ;;
     -status)
-      SHOW_STATUS=true
+      show_status
+      exit 1
       ;;
     -tacfile)
       # Change TAC file location
@@ -169,22 +191,6 @@ while true; do
   esac
 done
 
-if [ "$SHOW_STATUS" == "true" ]; then
-  if [ -e $PID_PATH/$PID_FILE ]; then
-    mypid=`cat $PID_PATH/$PID_FILE`
-    if kill -0 &>1 > /dev/null $mypid; then
-      echo "Yombo gateway appears to be running with pid: $mypid"
-      echo ""
-      $SCRIPTPATH/scripts/show_motd
-      exit 1
-    fi
-    echo "Yombo gateway is not running."
-  fi
-  exit 1
-fi
-
-YOMBO_SERVICE="echo \"$ARGUMENTS\" | twistd --pidfile=$PID_PATH/$PID_FILE"
-
 #Check if PID is running, if it is, then exit gracefully.
 if [ -e $PID_PATH/$PID_FILE ]; then
     mypid=`cat $PID_PATH/$PID_FILE`
@@ -194,33 +200,38 @@ if [ -e $PID_PATH/$PID_FILE ]; then
   fi
 fi
 
-if [ $DAEMON -eq "0" ]; then
-   YOMBO_SERVICE="$YOMBO_SERVICE -n"
+#YOMBO_SERVICE="echo \"$ARGUMENTS\" | twistd --pidfile=$PID_PATH/$PID_FILE"
+TACOPTIONS="--pidfile=$PID_PATH/$PID_FILE -n -y $TACFILE"
+
+if [ $DAEMON -eq "1" ]; then
+    YOMBO_SERVICE="echo \"$ARGUMENTS\" | $SCRIPTPATH/yombo_tac.sh $TACOPTIONS --logfile=$LOGFILE &"
+    eval $YOMBO_SERVICE
+    exit 0
 else
-   YOMBO_SERVICE="$YOMBO_SERVICE --logfile=$LOGFILE"
-fi
+    YOMBO_SERVICE="echo \"$ARGUMENTS\" | twistd $TACOPTIONS"
+    cd $SCRIPTPATH
+    export SSL_CERT_FILE="$(python -m certifi)"
 
+    echo "checking pyenv"
+    #Check if pyenv is being used and isn't loaded...
+    if [ -f ".python-version" ] ; then
+      if ! [ -x "$(command -v pyenv)" ]; then
+        echo "Yombo.sh setting up pyenv"
+        export PATH="~/.pyenv/bin:$PATH"
+        eval "$(pyenv init -)"
+        eval "$(pyenv virtualenv-init -)"
+      fi
+    fi
 
-export SSL_CERT_FILE="$(python -m certifi)"
-YOMBO_SERVICE="$YOMBO_SERVICE -y $TACFILE"
-
-#Check if pyenv is being used and isn't loaded...
-if [ -f ".python-version" ] ; then
-  if ! [ -x "$(command -v pyenv)" ]; then
-    echo "Yombo.sh setting up pyenv"
-    export PATH="~/.pyenv/bin:$PATH"
-    eval "$(pyenv init -)"
-    eval "$(pyenv virtualenv-init -)"
-  fi
+   echo "starting daemon! $YOMBO_SERVICE"
+#   eval $YOMBO_SERVICE
+#   ps aux | grep twis
+#   exit 1
 fi
 
 while :
 do
-  if [ $DAEMON -eq "1" ]; then
-     eval $YOMBO_SERVICE
-  else
-     eval $YOMBO_SERVICE
-  fi
+  eval $YOMBO_SERVICE
   OUT=$?
   if [ $OUT -le "126" ]; then
     # Gateway died for some reason or was told to quit, so, lets exit!
